sophgo/linux-riscv

arch/riscv/boot/dts/sophgo/mango-2sockets.dtsi
arch/riscv/boot/dts/sophgo/mango.dtsi

The mango use seperate timer and ipi dtb node to provide device, fix them with the correct value.
The existed timer use a special compatible "riscv,mango-timer", replace this with per cluster "thead,c900-clint-mtimer" device.
Replace "riscv,aclint-mswi" with "thead,c900-clint-mswi" to avoid potential errors.

riscv: dts: sophgo: fix timer and ipi device

---

arch/riscv/boot/dts/sophgo/mango-pcie-2rc.dtsi
arch/riscv/boot/dts/sophgo/mango-pcie-3rc-v2.dtsi
arch/riscv/boot/dts/sophgo/mango-pcie-3rc.dtsi
arch/riscv/boot/dts/sophgo/mango-pcie-4rc.dtsi
arch/riscv/boot/dts/sophgo/mango-sophgo-pisces.dts
arch/riscv/boot/dts/sophgo/mango-top-intc2.dtsi
arch/riscv/boot/dts/sophgo/mango.dtsi
drivers/pci/controller/cadence/pcie-cadence-sophgo.c
drivers/pci/controller/cadence/pcie-cadence-sophgo.h
drivers/soc/sophgo/top/top_intc.c

driver:pcie: enable top intc of chip1 for server

driver:pcie: enable top intc of chip1 for server

---

drivers/net/ethernet/stmicro/stmmac/dwmac-sophgo.c

do not modify eth phy config when phydev is NULL.

[ethernet]: bug fix

---

arch/riscv/boot/dts/sophgo/mango.dtsi

As the PMU events described in T-HEAD document have some mistake. Fix this events with information from T-HEAD vendor kernel driver.

riscv: sophgo: change PMU definition

---

arch/riscv/boot/dts/sophgo/mango-pcie-2rc.dtsi

This is a workround for the PMC switch hang when to access device linked to its DSP

riscv:dts: split socket0 pcie1 into double x8 mode for pisces

---

arch/riscv/boot/dts/sophgo/mango-pcie-2rc.dtsi
drivers/pci/controller/cadence/pcie-cadence-sophgo.c

riscv: dts: sophgo: Set PCIE1 to support msix

drivers: pcie: Add switchtec to the PCIE MSIX whitelist

---

tools/lib/perf/cpumap.c

These are loop counters which is inherently unsigned. Therefore make them unsigned. Moreover it also fixes alloc-size-larger-than error with gcc-13, where malloc can be called with (-1) due to tmp_len being an int type.
Fixes
| cpumap.c:366:20: error: argument 1 range [18446744065119617024, 18446744073709551612] exceeds maximum object size 9223372036854775807 [-Werror=alloc-size-larger-than=]
|   366 |         tmp_cpus = malloc(tmp_len * sizeof(struct perf_cpu));
|       |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
refer: https://www.spinics.net/lists/linux-perf-users/msg25755.html
patch: https://git.yoctoproject.org/poky/plain/meta/recipes-kernel/linux/files/0001-perf-cpumap-Make-counter-as-unsigned-ints.patch

perf cpumap: Make counter as unsigned ints

---

kernel/time/tick-oneshot.c

set the print level of the switch_to oneshot function to DEBUG

kernel: tick: filter unnecessary printing

---

arch/riscv/kernel/cpufeature.c

The variable for hiding v0p7 needs to be set BEFORE the ISA set initialzation, so use early_param instead of __setup .

riscv: fix v0p7 hiding

---

arch/riscv/boot/dts/sophgo/sg2260-ap-pld.dts
drivers/net/ethernet/stmicro/stmmac/dwmac-sophgo.c

1) remove thead extension in cpu node
2) replace riscv,plic0 to thead,c900-pic
3) make interrupts prop two cell
4) add xlgmac configuration in dts and dwmac-sophgo.c.

dts:sg2260: Modify ap dts and add xlgmac driver code.

---

drivers/pci/controller/cadence/pcie-cadence-sophgo.c
include/linux/mlx4/device.h

Basic functionalities have been tested to work fine on pioneer board.

pcie: whitelist and support mellanox connectx-2

---

kernel/sched/core.c

Reason:The SG2260 multimedia module requires the thread priority setting function
This reverts commit 616d91b68cd56bcb1954b6a5af7d542401fde772.

Revert "sched: Remove sched_setscheduler*() EXPORTs"

---

arch/riscv/boot/dts/sophgo/sg2260-ap-pld.dts
arch/riscv/boot/dts/sophgo/sg2260-rp-pld.dts
arch/riscv/boot/dts/sophgo/sg2260-tp-pld.dts
drivers/clk/sophgo/clk.c

1. set uart frequency to 500000000.
2. uart get clk by clk tree.
3. add current-speed node for opensbi and kernel set uart baud.
4. set uart baud 115200 in bootarg.
5. add this modify to rp and tp.
6. fix uninit warning when compile in drivers/clk/sophgo/clk.c.

riscv:dts 2044 bringup set default uart config.

---

drivers/clk/sophgo/clk.h

1. max ref div clk value is 63, max fb div clk value is 1066, min fb div clk value is 8.
2. pll ctrl register bit30/28/24 have default value 1.

riscv:drivers:clk: set SG2044 clk register default value.

---

arch/riscv/boot/dts/sophgo/sg2044-clock.dtsi
arch/riscv/boot/dts/sophgo/sg2260-ap-pld.dts
drivers/clk/sophgo/clk-sg2044.c
drivers/clk/sophgo/clk.c
drivers/tty/serial/8250/8250_dw.c

1. let top_misc before soc node.
2. do not modify pll.
3. uart do not need dw8250_set_termios.

riscv:driver:clk: fix SG2044 clk tree bugs.

---

arch/riscv/boot/dts/sophgo/sg2044-clock.dtsi
arch/riscv/boot/dts/sophgo/sg2260-peri-sys.dtsi
arch/riscv/boot/dts/sophgo/sg2260-rp-full.dts
drivers/clk/clk.c
drivers/clk/sophgo/clk-sg2044.c
drivers/clk/sophgo/clk.c
drivers/clk/sophgo/clk.h
drivers/net/ethernet/stmicro/stmmac/dwmac-sophgo.c

1. parent clk should have CLK_IS_CRITICAL attribute for keep clk enable.
2. add mofidy pll function to let user use debugfs set mpll freq. when modify pll freq, must switch target pll to backup pll, then set the pll freq, finally switch back to target pll.
3. add clk for 100GE mac driver init.
4. now default peri dts have 4 uart, rp will use uart1, so let the bootargs also use ttyS1.
5. let rp default use 64 maxcpus in bootargs.
6. fix pll default frequency uncorrect bugs, the frequency should be calculate by (postdiv1 - 1) and (postdiv2 - 1).

riscv:drivers:clk: fix system hang bug in Ubuntu bringup.

---

drivers/clk/sophgo/clk.c
drivers/clk/sophgo/clk.h

pll control register bit[17:16] is for vcosel, if vcosel is 0x2, pll range is 1.6G~2.4GHz, if vcosel is 0x3, pll range is 2.4G~ 3.2GHz. we must modify this bit when set pll values and limit the pll range 1.6G ~ 3.2GHz.

riscv:drivers:clk fix pll can't set value greater then 2.4G

---

arch/riscv/boot/dts/sophgo/bm1690-evb.dts
arch/riscv/boot/dts/sophgo/sg2260-ap-full.dts
arch/riscv/boot/dts/sophgo/sg2260-rp-full.dts

SG2044 use the master branch code of Opensbi, same as SG2042.

riscv: dts: update SG2044 reset/poweroff dts node name

---

drivers/mtd/spi-nor/controllers/sophgo-spifmc.c

- data read is divided into 64k due to IP restrictions that reg TRANS_NUM is 16bit

driver: spifmc: fix spif bug when bs of dd exceed 64k

---

drivers/mmc/host/sdhci-sophgo.c

- found that using the new phy config for evbs that only support 3.3V would errors
Signed-off-by: kun-chang <kun.chang@sophgo.com>

driver: mmc: fallback the configuration of phy in sdhci-sophgo.c

---

arch/riscv/kernel/cpufeature.c

When `CONFIG_VECTOR=n`, we should remove the 'v' bit from the ELF capabilities. This lets userspace detect its absence, and (for example) fixes the default build of FFmpeg. I've also made a cosmetic change to fix a compiler warning; the individual commit messages have more information.

Remove 'v' from ELF caps when CONFIG_VECTOR=n

---

drivers/clk/sophgo/clk-sg2044.c

When SG2044 use linuxboot, first step linux exit will close the cxp clk, this will cause second step linux hang when it visit cxp register, so we keep the cxp clk enable so that first step linux don't close the clk gate.

riscv: drviers: clk: sg2044 keep cxp clk enable.

---

drivers/soc/sophgo/ap_sgcard/ap_sgcard.c
drivers/tty/Kconfig

1. new line should be at the end of drivers/tty/Kconfig.
2. In ap_sgcard.c:440, the type is long long unsigned.

drivers: soc: sophgo: eliminate compile warnings.

---

arch/riscv/boot/dts/sophgo/bm1690-cdm-rp.dts

In BM1690 PCIe mode, rp memory map is same as rp soc mode.

dts: sophgo: update rp dts that used by bm1690 soc.

---

arch/riscv/boot/dts/sophgo/sg2044-peri-sys.dtsi

We need 1 normal interrupt, 8 tx interrupts and 8 rx interrupts for 100GE.

dts:riscv: fix interrupts register bug.

---

arch/riscv/boot/dts/sophgo/bm1690-cdm-rp.dts

zsbl address: 0x1d4000000
opensbi address: 0x1c0000000
kernel address: 0x1c0200000
dtb address: 0x1c8000000
ramfs address: 0x1cb000000

dts: riscv: In bm1690 pcie mode, change rp used memory.

---

arch/riscv/include/asm/errata_list.h

KUnit test error:
arch/riscv/mm/dma-noncoherent.c:54:
Error: unrecognized opcode cbo.clean (a0)', extension zicbom' required
Related commit: 
1. [RISC-V: replace cbom instructions with an insn-def](https://github.com/sophgo/linux-riscv/commit/dd23e95)
2. [riscv: cpufeature: extend riscv_cpufeature_patch_func to all ISA extensions](https://github.com/sophgo/linux-riscv/commit/4bf8860)
Related issue: <https://github.com/sophgo/linux-riscv/issues/282>.

fix: KUnit Error: unrecognized opcode cbo.clean (a0)

---

drivers/irqchip/irq-sg2044-msi.c

By modifying the corresponding acpi table, 512 MSIs have been supported now.

drivers: irqchip: modify "MAX_IRQ_NUMBER" to 512

---

drivers/irqchip/irq-sg2044-msi.c

SG2044 is PLIC based platforms, which means it doesn't support MSI natively. PCIe MSIs should routed to a dedicated MSI controller. This MSI controller wire interrupts to PLIC. So PCIe host need such MSI controller initialized before.
This commit deal with dependency delcared in ACPI DSDT. Linux kernel drivers of MSI controller should use
acpi_dev_clear_dependencies to nofity ACPI probe framework that it has done. After which, ACPI probe continue with PCIe hosts.

SG2044 MSI: ACPI:

---

drivers/of/fdt.c

The EFI Stub will generate an empty DTB and append the /chosen node to it when booting ARM64 and RISC-V platfroms with ACPI enabled. That means the DTB is not empty.
The commit 7b937cc ignores the above ACPI boot situation, which forces the fdt to be NULL when ACPI is enabled, resulting in the following issue.
[    3.491475] OF: fdt: not creating '/sys/firmware/fdt': CRC check failed

of: fdt: Fix fdt CRC check failed when ACPI is enabled

---

drivers/acpi/scan.c

- We found that the previous dependency description for PCI was incomplete, as there is a description of INTX functionality in PCI in ACPI, resulting in the "honor_deps" being seen as true. In fact, now the '_DEP' described in the ACPI table does not exist in "acpi_honor_dep_ids" when checked in the kernel, and this dependency is invalid. When we remove the description of INTX functionality in ACPI, the previous PCI device will still be probed before the MSI controller and unable to function properly.
- We should ensure that all dependencies added to the device are valid, and all dependencies are probed before the device.
- Like:"Interrupt controller <-- Link Device + MSI Controller <-- PCI Host bridge".

drivers: acpi: add MSI controller's HID to acpi_honor_dep_ids

---

arch/riscv/boot/dts/sophgo/bm1690-evb-ap.dts
arch/riscv/boot/dts/sophgo/bm1690-evb.dts

dts: sophgo: let each cpu only use one uart.

---

drivers/pci/controller/dwc/pcie-dw-sophgo.c

- When ACPI CONFIG is ture, the kernel supports ACPI and DTB.
- When ACPI CONFIG is false, the kernel compiles through and the kernel only supports DTB.

drivers: pci: controller: dwc: adapt to ACPI and DTB

---

drivers/irqchip/Makefile
drivers/irqchip/irq-thead-c900-aclint-sswi.c

Add ACPI support in ACLINT-SSWI early probe. Treat ACLINT-SSWI as a fake IMSIC that can only handle IPIs in a software manner. Use the IMSIC-related fields in the MADT table to obtain the register base address of ACLINT-SSWI.
Note that when booting with ACPI, ACLINT-SSWI cannot coexist with the standard IMSIC driver, as the IMSIC driver parses the ACPI table entries before ACLINT-SSWI, resulting in error logs. Therefore, we disable the IMSIC-related kernel drivers.

irqchip/thead-c900-aclint-sswi: Add ACPI support

---

arch/riscv/boot/dts/sophgo/sg2042-milkv-pioneer.dts

There is a power button on the front panel of the pioneer box. Short pressing the button will trigger the onboard MCU to notify SG2042 through GPIO22 to enter the power-off process.
Patch from https://lore.kernel.org/all/cover.1728350655.git.unicorn_wang@outlook.com/

riscv: sophgo: dts: add power key for pioneer box

---

drivers/clk/sophgo/clk.c

1. delete read operation before write the pll register.
2. format the description of the function.

riscv: drivers: clk: clk register don't need read before write.

---

drivers/acpi/acpi_apd.c
drivers/i2c/busses/i2c-designware-platdrv.c
drivers/spi/spi-dw-mmio.c

- Revert the previous compatible modification of SPI.
- Add SOPH0003 and SOPH0004 to the ACPI APD support list to ensure correct clock settings for the I2C and SPI devices on the SOPHGO platforms.

drivers: Add i2c and spi ACPI support

---

drivers/irqchip/irq-sifive-plic.c

Sort out the loading order of PCIe dependencies and fix the warning caused by a race condition between the delayed execution of the PCIe driver and pci_sysfs_init when the dependencies are not satisfied.
[ 5.085835] sysfs: cannot create duplicate filename '/devices/pci0002:00/0002:00:00.0/resource0' [ 5.106935] CPU: 17 UID: 0 PID: 521 Comm: kworker/u274:2 Not tainted 6.12.14-0.0.0.0.riscv64 #1 [ 5.106943] Hardware name: SOPHGO SG2044EVB/SG2044EVB, BIOS [ 5.106948] Workqueue: events_unbound acpi_scan_clear_dep_fn [ 5.106962] Call Trace:
[ 5.106965] [<ffffffff80006ebe>] dump_backtrace+0x28/0x30 [ 5.106976] [<ffffffff80ddc3ca>] show_stack+0x38/0x44 [ 5.106986] [<ffffffff80df315e>] dump_stack_lvl+0x6a/0x82 [ 5.106993] [<ffffffff80df318e>] dump_stack+0x18/0x20 [ 5.106998] [<ffffffff8037d5d4>] …

drivers: adjust registration priority of riscv-plic driver

---

arch/riscv/Kconfig
arch/riscv/include/asm/acpi.h
arch/riscv/include/asm/fixmap.h
arch/riscv/include/asm/io.h

- Define arch_apei_get_mem_attribute() to provide memory protectiong bits for GHES physical address mapping.
- Implement ioremap_cache() required by BERT/EINJ drivers.
- Add fixmap indices for GHES IRQ context.
- Enable APEI config option to make GHES features visible.

riscv: add APEI GHES support for RAS

---

drivers/irqchip/Makefile
drivers/irqchip/irq-thead-c900-aclint-sswi.c

Add ACPI support in ACLINT-SSWI early probe. Treat ACLINT-SSWI as a fake IMSIC that can only handle IPIs in a software manner. Use the IMSIC-related fields in the MADT table to obtain the register base address of ACLINT-SSWI.
Note that when booting with ACPI, ACLINT-SSWI cannot coexist with the standard IMSIC driver, as the IMSIC driver parses the ACPI table entries before ACLINT-SSWI, resulting in error logs. Therefore, we disable the IMSIC-related kernel drivers.

drivers: Add ACPI support for thead-c900-aclint-sswi

---

drivers/pci/controller/cadence/pcie-cadence-sophgo.c

Signed-off-by: haijiao.liu <haijiao.liu@sophgo.com>
Fix compilation errors caused by function type mismatch.
drivers/pci/controller/cadence/pcie-cadence-sophgo.c:403:12: error: conflicting types for 'cdns_pcie_host_init'; have 'int(struct device *, struct cdns_mango_pcie_rc *)'
403 | static int cdns_pcie_host_init(struct device *dev, struct cdns_mango_pcie_rc *rc)
|            ^~~~~~~~~~~~~~~~~~~
In file included from drivers/pci/controller/cadence/pcie-cadence-sophgo.c:16:
drivers/pci/controller/cadence/pcie-cadence.h:519:5: note: previous declaration of 'cdns_pcie_host_init' with type 'int(struct cdns_pcie_rc *)'
519 | int cdns_pcie_host_init(struct cdns_pcie_rc *rc);
|     ^~~~~~~~~~~~~~~~~~~

pcie: fix pcie-cadence-sophgo.c build error

---

drivers/irqchip/irq-sifive-plic.c

Sort out the loading order of PCIe dependencies and fix the warning caused by a race condition between the delayed execution of the PCIe driver and pci_sysfs_init when the dependencies are not satisfied.
[ 5.085835] sysfs: cannot create duplicate filename '/devices/pci0002:00/0002:00:00.0/resource0' [ 5.106935] CPU: 17 UID: 0 PID: 521 Comm: kworker/u274:2 Not tainted 6.12.14-0.0.0.0.riscv64 #1 [ 5.106943] Hardware name: SOPHGO SG2044EVB/SG2044EVB, BIOS [ 5.106948] Workqueue: events_unbound acpi_scan_clear_dep_fn [ 5.106962] Call Trace:
[ 5.106965] [<ffffffff80006ebe>] dump_backtrace+0x28/0x30 [ 5.106976] [<ffffffff80ddc3ca>] show_stack+0x38/0x44 [ 5.106986] [<ffffffff80df315e>] dump_stack_lvl+0x6a/0x82 [ 5.106993] [<ffffffff80df318e>] dump_stack+0x18/0x20 [ 5.106998] [<ffffffff8037d5d4>] …

drivers: Fix an warning handling path in acpi_scan_clear_dep_fn()

---

drivers/acpi/acpi_apd.c
drivers/i2c/busses/i2c-designware-platdrv.c

Add SOPH0003 to the ACPI APD support list to ensure correct clock settings for the I2C devices on the Sophgo SG2044 platforms.

drivers: i2c: Add ACPI support for Sophgo I2C Controller

---

drivers/acpi/acpi_apd.c
drivers/spi/spi-dw-mmio.c

Add SOPH0004 to the ACPI APD support list to ensure correct clock settings for the SPI devices on the Sophgo SG2044 platforms.

drivers: spi: Add ACPI support for Sophgo SPI Controller

---

net/core/datagram.c

In the SKB driver,  highmem is exposed to user space when use 'kmap' to alloc the whole frag in riscv arch, it triggers the usercopy mechanism.

net: fix skb_datagram_iter highmem problem

---

kernel/irq/ipi-mux.c

SG2042 server has 128 CPUs, but it may hang at the following position during startup. Add code to avoid this problem.
[    0.722843] cpu1: Ratio of byte access time to unaligned word access is 5.07, unaligned accesses are fast
[    0.792854] cpu2: Ratio of byte access time to unaligned word access is 5.16, unaligned accesses are fast

irq: ipi-mux: Avoid the problem of smp startup hanging

---

drivers/pci/controller/dwc/pcie-dw-sophgo.c

The commit "sophgo/dw-pcie: Remove buggy static variable phb_dev" accidentally removed the critical assignment `pcie->dev = dev;` in sophgo_pcie_init().

sophgo/dw-pcie: Restore dev assignment for resources access

---

drivers/pci/controller/dwc/pcie-dw-sophgo.c

The original implementation of pci_host_bridge_acpi_get_fwnode() incorrectly returned the fwnode. This caused pcie msi domain setting failures.

pcie: Fix incorrect fwnode return

---

arch/riscv/Kconfig

This adds a separate segment for kernel text in /proc/kcore, which has a different address than the direct linear map.
Link: https://lore.kernel.org/r/mvmh6m758ao.fsf@suse.de

riscv: select ARCH_PROC_KCORE_TEXT
