sophgo/linux-riscv

arch/riscv/boot/dts/sophgo/mango-pcie-2rc.dtsi, arch/riscv/boot/dts/sophgo/mango-pcie-3rc.dtsi, arch/riscv/boot/dts/sophgo/mango-pcie-4rc.dtsi, arch/riscv/boot/dts/sophgo/mango-sophgo-pisces.dts, drivers/pci/controller/cadence/pcie-cadence-sophgo.c
1. driver:pcie: add pcie dtsi configuring for 2 chips server
2. driver:pcie: support top interrupt controller configurable for PCIe RP controller
=> driver:pcie:support two chips server

arch/riscv/boot/dts/sophgo/mango-pcie-3rc-v2.dtsi, arch/riscv/boot/dts/sophgo/mango-sophgo-x4evb.dts, drivers/pci/controller/cadence/pcie-cadence-sophgo.c
driver:pcie: support x4evb topo
=> driver:pcie: support x4evb topo

drivers/pci/controller/cadence/pcie-cadence-sophgo.c
driver:pcie: add link1 interrupt handling implementation
=> driver:pcie: add link1 interrupt handling implementation

arch/riscv/boot/dts/sophgo/mango-pcie-3rc-v2.dtsi
driver:pcie: modify the interrupt mode of pcie0 link1 for x4evb
=> driver:pcie: modify the interrupt mode of pcie0 link1 for x4evb

drivers/net/ethernet/stmicro/stmmac/dwmac-sophgo.c
driver:net: increase time delay for eth0 phy reset
=> driver:net: increase time delay for eth0 phy reset

arch/riscv/boot/dts/sophgo/mango-pcie-2rc.dtsi, arch/riscv/boot/dts/sophgo/mango-pcie-3rc-v2.dtsi, arch/riscv/boot/dts/sophgo/mango-pcie-3rc.dtsi, arch/riscv/boot/dts/sophgo/mango-pcie-4rc.dtsi, drivers/pci/controller/cadence/pcie-cadence-sophgo.c
driver:pcie: support msix for top intr
=> driver:pcie: support msix for top intr

arch/riscv/boot/dts/sophgo/sg2260-ap-pld.dts
sg2260 ap mswi base address is 0x6e04000000, mtimer base address is 0x6840000000.
=> [2260]: adapte for sg2260 mswi and mtimer

drivers/rtc/rtc-astbmc.c
1. Increase timeout return strategy when reading RTC time;
2. Detect the status of BMC before registering RTC devices.
=> kernel drivers/rtc/rtc-astbmc.c:

drivers/pci/controller/cadence/pcie-cadence-sophgo.c
dirvers:pci:remove the err log of parsing pci
=> drivers:pci:remove the err log of parsing pci

arch/riscv/boot/dts/sophgo/sg2260-rp-pld.dts
add host driver note in rp dtb
add sg2260_host_driver note in dtb
=> add host driver note in rp dtb

arch/riscv/boot/dts/sophgo/sg2260-ap-pld.dts, arch/riscv/boot/dts/sophgo/sg2260-rp-pld.dts, drivers/net/ethernet/stmicro/stmmac/dwmac-sophgo.c
1.mac disable rx/tx delay
2.phy enable rx/tx delay
=> driver:ethernet:add tx/rx delay ctl in mac

arch/riscv/boot/dts/sophgo/sg2260-pcie-5rc-rp.dtsi
change C2C1 base address to 0x6c04-xxxx-xxxx
=> change C2C1 base address to 0x6c04-xxxx-xxxx

drivers/perf/riscv_pmu_sbi.c
The 6.1.31 branch also needs to merge this commit.
=> add null event check logic in riscv_pmu_sbi.c

scripts/package/builddeb
- revert "make headers package thinner"
- add module sign certificate and System.map
https://kernel.source.codeaurora.cn/pub/scm/linux/kernel/git/ stable/linux.git/commit/?id=9945722afdc3443eab826b2da1122509a13a50a5
=> script: make headers package fatter

tools/sophgo/pmbus/Makefile, tools/sophgo/pmbus/pmbus.c
add pmbus.c and Makefile to linux-rsicv/tools/sophgo/pmbus directory.
used to read or write power management chip registers via iic bus.
can dump Iout, Vout, temprature and Pout data from the chip.
=> add pmbus debugging tool

arch/riscv/boot/dts/sophgo/sg2044-pcie-5rc-rp.dtsi, drivers/pci/controller/dwc/pcie-dw-sophgo.c
change symbol 2260 to 2044 in the file
=> change symbol 2260 to 2044 in the file

arch/riscv/kernel/cpufeature.c, arch/riscv/kernel/vector.c
riscv: xtheadvector: fix setup_v_vsize
=> fix: riscv: xtheadvector: fix setup_v_vsize

tools/sophgo/efuse_test/Makefile, tools/sophgo/efuse_test/argvtoint.c, tools/sophgo/efuse_test/argvtoint.h, tools/sophgo/efuse_test/debug.h, tools/sophgo/efuse_test/devmem.c, tools/sophgo/efuse_test/devmem.h, tools/sophgo/efuse_test/efuse.c, tools/sophgo/efuse_test/efuse.h
- support efuse writing, each bit can only be written onece
- support efuse reading
- note: addr is the Hard Macro address not Ecc read address
=> tools: efuse: add efuse code used in user-mode

drivers/soc/sophgo/pcie_ep/bm1690_ep_init.c
drivers:soc:support multi msi for sc11
=> drivers:soc:support multi msi for sc11

arch/riscv/boot/dts/sophgo/bm1690-cdm-ap.dts
add veth rp to ap in bm1690 evb soc mode
=> add veth rp to ap in bm1690 evb soc mode

drivers/mtd/spi-nor/controllers/sophgo-spifmc.c
- data read is divided into 64k due to IP restrictions that reg TRANS_NUM is 16bit
=> driver: spifmc: fix spif bug when bs of dd exceed 64k

drivers/mfd/syscon.c, include/linux/mfd/syscon.h
riscv: add ACPI support for syscon
=> add ACPI support for syscon

drivers/pci/controller/cadence/pcie-cadence-sophgo.c
drivers:pci: SC11 support msi-x
=> drivers:pci: SC11 support msi-x

arch/riscv/boot/dts/sophgo/sg2044-pcie-5rc.dtsi, drivers/pci/controller/dwc/pcie-dw-sophgo.c, drivers/pci/controller/dwc/pcie-dw-sophgo.h
pcie supports legacy interrupts
=> pcie supports legacy interrupts

drivers/irqchip/irq-sg2044-msi.c
The acpi table currently only supports declaring 255 MSI interrupts,
so here, modify "MAX_SIRQ-NUMBER" to 255 temporarily.
=>  drivers: irqchip: add ACPI support for SG2044

arch/riscv/boot/dts/sophgo/sg2044-peri-sys.dtsi, drivers/crypto/Kconfig, drivers/crypto/Makefile, drivers/crypto/dwc/Makefile, drivers/crypto/dwc/dwc-ecc.c, drivers/crypto/dwc/dwc-ecdh.c, drivers/crypto/dwc/dwc-ecdsa.c, drivers/crypto/dwc/dwc-elperror.c, drivers/crypto/dwc/dwc-elperror.h, drivers/crypto/dwc/dwc-elppka.c, drivers/crypto/dwc/dwc-elppka.h, drivers/crypto/dwc/dwc-elppka_elf.h, drivers/crypto/dwc/dwc-firmware.c, drivers/crypto/dwc/dwc-pka.c, drivers/crypto/dwc/dwc-pka.h, drivers/crypto/dwc/dwc-pkacommon.c, drivers/crypto/dwc/dwc-pkahw.h, drivers/crypto/dwc/dwc-rsa.c, include/linux/asn1_decoder.h
drivers: pka: implement algs within crypto alg framework using snps,designware hardware
crypto: including algs: rsa, ecdh(192, 256, 384), ecdsa(192, 256, 384)
ecdsa 521 curve has not been implemented yet
it can successfully probe and register, but can not pass testmgr tests provided by linux kernel
=> unverified driver for rsa and ecc algorithm

arch/riscv/boot/dts/sophgo/bm1690-tpu-sys.dtsi
align compatible name with 6.12 branch.
=> dts: modify tpu compatible

arch/riscv/boot/dts/sophgo/sg2044-pcie-5rc.dtsi
=> correct pcie node name
